# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: interface                  # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Plugin zur Steuerung von NSPanels, die mit Tasmota und LoveLaceUI ausgestattet sind. Die Kommunikation erfolgt über das MQTT Module von SmartHomeNG.'
        en: 'Plugin to control NSPanels equipped with Tasmota firmware and LoveLaceUI. Communication is handled through the MQTT module of SmartHomeNG.'
    maintainer: sisamiwe
#    tester:                         # Who tests this plugin?
    state: develop                   # change to ready when done with development
#    keywords: iot iot
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.0.0                  # Plugin version
    sh_minversion: 1.8              # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
#    py_minversion: 3.6             # minimum Python version to use for this plugin
#    py_maxversion:                 # maximum Python version to use for this plugin (leave empty if latest)
    multi_instance: true            # plugin supports multi instance
    restartable: unknown
    classname: NSPanel         # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)
    full_topic:
        type: str
        default: '%prefix%/%topic%/'
        description:
            de: Vollständiges Topic (Prefix und Topic) zur Kommunikation mit den NSPanel
            en: Full topic (prefix und topic) for communication with NSPanel

    topic:
        type: str
        default: 'NSPanel1'
        description:
            de: Topic des NSPanel
            en: topic of NSPanel

    telemetry_period:
        type: int
        default: 300
        valid_min: 10
        valid_max: 3600
        description:
            de: Zeitabstand in Sekunden in dem das NSPanel Telemetrie Daten senden sollen
            en: Timeperiod in seconds in which the NSPanel shall send telemetry data

    config_file_location:
        type: str
        description:
            de: 'Speicherort der Konfigurationsdatei relativ zum smarthome Ordner bspw: /usr/local/smarthome/plugins/_priv_nspanel/nspanel_pages.yaml'
            en: 'Location of Config_file relatively to smarthome directory e.g. /usr/local/smarthome/plugins/_priv_nspanel/nspanel_pages.yaml'

    webif_pagelength:
        type: int
        valid_list:
          - -1
          - 0
          - 25
          - 50
          - 100
        description:
            de: 'Anzahl an Items, die standardmäßig in einer Web Interface Tabelle pro Seite angezeigt werden.
                 0 = automatisch, -1 = alle'
            en: 'Amount of items being listed in a web interface table per page by default.
                 0 = automatic, -1 = all'
        description_long:
            de: 'Anzahl an Items, die standardmäßig in einer Web Interface Tabelle pro Seite angezeigt werden.\n
                 Bei 0 wird die Tabelle automatisch an die Höhe des Browserfensters angepasst.\n
                 Bei -1 werden alle Tabelleneinträge auf einer Seite angezeigt.'
            en: 'Amount of items being listed in a web interface table per page by default.\n
                 0 adjusts the table height automatically based on the height of the browser windows.\n
                 -1 shows all table entries on one page.'

item_attributes:

    nspanel_topic:
        type: str
        description:
            de: Topic um mit dem NSPanels zu kommunizieren (%topic%)
            en: Topic to be used to communicate with the NSPanels (%topic%)

    nspanel_attr:
        type: str
        default: online
        description:
            de: "Zu lesendes/schreibendes Attribut des NSPanels."
            en: "Attribute of NSPanels shall be read/written."
        valid_list:
            - online
            - temp_analog
            - temp_esp32
            - power1
            - power2

    nspanel_popup:
        type: str
        default: notify
        description:
            de: "Pageunabhängige Items des NSPanels."
            en: "Page independent item of NSPanel."
        valid_list:
            - notify
            - timer
        valid_list_description:
            de:
              - "Inhalt wird als PopupNotify angezeigt.-> dict, w/o"
              - "Item wird als Zähler für PopupTimer verwendet -> num, r/o"

item_structs:
    nspanel:
        online:
            type: bool
            nspanel_topic@instance: ..:.
            nspanel_attr@instance: online

        temperature_analog:
            type: num
            nspanel_topic@instance: ..:.
            nspanel_attr@instance: temp_analog

        temperature_esp32:
            type: num
            nspanel_topic@instance: ..:.
            nspanel_attr@instance: temp_esp32

        notify:
            type: dict
            nspanel_popup@instance: notify

        timer:
            type: num
            nspanel_popup@instance: timer

        chart:
            type: list
            eval: sh.env.system.load.series('avg', '1d', count=50).get('series') # only example for format of data

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)
